/*
 * Copyright (c) 2023 Apple Inc. All rights reserved.
 * Apple Pay JS Software
 * 
 * **IMPORTANT:** This Apple Pay JS Software (the "Apple Software") is supplied to you by Apple Inc. ("Apple") in consideration of your agreement to the following terms, and your use, reproduction, or installation of this Apple Software constitutes acceptance of these terms. If you do not agree with these terms, do not use, reproduce or install this Apple Software.
 * 
 * This Apple Software is licensed to you solely for: (a) use with the Apple Pay button that you are authorized or legally permitted to embed or display on your website and (b) the purposes set forth above, and may not be used for other purposes or in other contexts without Apple's prior written permission. For the sake of clarity, you may not and agree not to or enable others to, modify or create derivative works of the Apple Software.
 * 
 * You may only use the Apple Software if you are a member in good standing of the Apple Developer Program and have accepted the current version of the Apple Developer Program License Agreement. Your use of the Apple Software must conform with the Acceptable Use Guidelines for Apple Pay on the Web, located at https://developer.apple.com/apple-pay/acceptable-use-guidelines-for-websites/, which terms may be updated from time to time.
 * 
 * Neither the name, trademarks, service marks or logos of Apple may be used to endorse or promote products or services without specific prior written permission from Apple. Except as expressly stated in this notice, no other rights or licenses, express or implied, are granted by Apple herein.
 * 
 * Apple may provide access to services by or through the Apple Software for you to use.  You agree that the services contain proprietary content, information and material that is owned by Apple and its licensors, and is protected by applicable intellectual property and other laws, and that you will not use such proprietary content, information or materials in any way whatsoever except for permitted use of the services or in any manner that is inconsistent with these terms or that infringes any intellectual property rights of a third party or Apple.  Except to the extent expressly permitted in the applicable terms for the services, You agree not to reproduce, modify, rent, lease, lend, sell, distribute, or create derivative works based on the services, in any manner, and you shall not exploit the services in any unauthorized way whatsoever, including but not limited to, using the services to transmit any malware, or by trespass or burdening network capacity. 
 * 
 * In addition, services that may be accessed, linked to or displayed through the Apple Software may not be available in all languages or in all countries. Apple makes no representation that any such services would be appropriate or available for use in any particular location. Apple reserves the right to change, suspend, remove, or disable access to any services at any time. In no event will Apple be liable for the removal of or disabling of access to any such services or for any updates, maintenance, warranty, technical or other support for such services. Apple may also impose limits or other restrictions on the use of or access to the services, in any case without notice or liability.  You acknowledge and agree that Apple reserves the right to revoke or remove your access to any services provided by or through the Apple Software at any time in its sole discretion.
 * 
 * THE APPLE SOFTWARE AND SERVICES ARE PROVIDED BY APPLE ON AN "AS IS" AND "AS AVAILABLE" BASIS. APPLE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS, SYSTEMS, OR SERVICES.  APPLE DOES NOT WARRANT THAT THE APPLE SOFTWARE AND SERVICES WILL MEET YOUR REQUIREMENTS, THAT THE OPERATION OF THE APPLE SOFTWARE AND SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS IN THE APPLE  SOFTWARE WILL BE CORRECTED, OR THAT THE APPLE  SOFTWARE AND SERVICES WILL BE COMPATIBLE WITH FUTURE APPLE PRODUCTS, SOFTWARE OR SERVICES. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY APPLE OR AN APPLE AUTHORIZED REPRESENTATIVE WILL CREATE A WARRANTY.
 * 
 * IN NO EVENT SHALL APPLE BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) RELATING TO OR ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION, OR INSTALLATION, OF THE APPLE SOFTWARE AND SERVICES BY YOU OR OTHERS, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event shall Apple’s total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00). The foregoing limitations will apply even if the above stated remedy fails of its essential purpose.
 * 
 * **ACKNOWLEDGEMENTS:**
 * https://applepay.cdn-apple.com/jsapi/v1.1.0/acknowledgements.txt
 * 
 * 10.6.2023
 */(function(){const p=document.currentScript;const e=()=>{const c={"apple-pay-button":"apple-pay-button.js","apple-pay-merchandising":"apple-pay-sdk.merchandising.js","apple-wallet-button":"apple-wallet-sdk.js"};const i=Object.keys(c).join(",");const e=p.getAttribute("data-initial-token")?.trim();const t=p.src.slice(0,p.src.lastIndexOf("/"))||"";const n=t?new URL(t).origin:"";const o=new URL(t);const s=o.pathname.substring(0,o.pathname.indexOf("/jsapi"));const a=`${n}${s}/jsapi/v1.1.0`;window.ApplePaySDK={token:e,publicPath:a};function r(e){const t=e.filter(e=>{return e.nodeType===Node.ELEMENT_NODE});t.forEach(e=>{const t=e.tagName.toLocaleLowerCase();if(t in c){import(`${a}/${c[t]}`)}})}const d=new MutationObserver((e,t)=>{for(const n of e){if(n.type==="childList"){for(const o of n.addedNodes){if(o.nodeType===Node.ELEMENT_NODE){const s=[...o.querySelectorAll(i)];const a=o.tagName.toLocaleLowerCase();if(a in c){s.push(o)}r(s)}}}}});r(Array.from(document.body.querySelectorAll(i)));d.observe(document.body,{childList:true,subtree:true})};if(document.readyState!=="loading"){e()}else{window.addEventListener("DOMContentLoaded",e)}})();